### ISSUE TITLE
Import "google/protobuf/descriptor.proto" was not found or had errors

### ISSUE THREAD

**Issue by soooldier** [storyicon/powerproto#3]
**protoc vertion 3.13.0**

配置文件这样：
```yaml
scopes:
    - ./
protoc: 3.13.0
protocWorkDir: ""
plugins:
    protoc-gen-go: google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
    protoc-gen-grpc-gateway: github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.5.0
    protoc-gen-micro: github.com/asim/go-micro/cmd/protoc-gen-micro/v3@bba3107ae13f
    protoc-gen-openapiv2: github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.5.0
repositories:
    GOOGLE_APIS: https://github.com/googleapis/googleapis@75e9812478607db997376ccea247dd6928f70f45
options:
    - --grpc-gateway_out=.
    - --grpc-gateway_opt=paths=source_relative
    - --openapiv2_out=.
importPaths:
    - .
    - $GOPATH
    - $POWERPROTO_INCLUDE
    - $SOURCE_RELATIVE
    - $GOOGLE_APIS/github.com/googleapis/googleapis
postActions: []
postShell: ""
```
xxx.proto里import了google/api下的proto文件：
```proto
import "google/api/annotations.proto";
import "google/api/field_behavior.proto";
```
执行`powerproto build xxx.proto` 报错：
```shell
google/protobuf/descriptor.proto: File not found.
google/api/annotations.proto:20:1: Import "google/protobuf/descriptor.proto" was not found or had errors.
google/api/annotations.proto:28:8: "google.protobuf.MethodOptions" is not defined.
google/api/field_behavior.proto:19:1: Import "google/protobuf/descriptor.proto" was not found or had errors.
google/api/field_behavior.proto:27:8: "google.protobuf.FieldOptions" is not defined.
```
